<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="CsvHelper" Version="33.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.17" />
    <PackageReference Include="Nager.Country" Version="4.0.0" />
    <PackageReference Include="Nager.Country.Translation" Version="3.1.0" />
    <PackageReference Include="NodaTime" Version="3.2.1" />
    <PackageReference Include="Microsoft.Extensions.Resilience" Version="9.1.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SoccerInfo.UnitTests" />
    <InternalsVisibleTo Include="SoccerInfo.IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SoccerInfo.Application.Abstractions\SoccerInfo.Application.Abstractions.csproj" />
    <ProjectReference Include="..\SoccerInfo.BackendScraper\SoccerInfo.BackendScraper.csproj" />
    <ProjectReference Include="..\SoccerInfo.Domain\SoccerInfo.Domain.csproj" />
    <ProjectReference Include="..\SoccerInfo.FrontendScraper\SoccerInfo.FrontendScraper.csproj" />
  </ItemGroup>

</Project>
