//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoccerInfo.FrontendScraper.ScrapePlayersGeneralInfo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LeagueLink {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LeagueLink() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoccerInfo.FrontendScraper.ScrapePlayersGeneralInfo.LeagueLink", typeof(LeagueLink).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.transfermarkt.pl/bundesliga/startseite/wettbewerb/A1.
        /// </summary>
        internal static string AustrianBundesliga {
            get {
                return ResourceManager.GetString("AustrianBundesliga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.transfermarkt.pl/bundesliga/startseite/wettbewerb/L1.
        /// </summary>
        internal static string Bundesliga {
            get {
                return ResourceManager.GetString("Bundesliga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.transfermarkt.pl/pko-bp-ekstraklasa/startseite/wettbewerb/PL1.
        /// </summary>
        internal static string Ekstraklasa {
            get {
                return ResourceManager.GetString("Ekstraklasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.transfermarkt.pl/eredivisie/startseite/wettbewerb/NL1.
        /// </summary>
        internal static string Eredivisie {
            get {
                return ResourceManager.GetString("Eredivisie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.transfermarkt.pl/jupiler-pro-league/startseite/wettbewerb/BE1.
        /// </summary>
        internal static string JupilerProLeague {
            get {
                return ResourceManager.GetString("JupilerProLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.transfermarkt.pl/laliga/startseite/wettbewerb/ES1.
        /// </summary>
        internal static string LaLiga {
            get {
                return ResourceManager.GetString("LaLiga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.transfermarkt.pl/liga-portugal/startseite/wettbewerb/PO1.
        /// </summary>
        internal static string LigaPortugal {
            get {
                return ResourceManager.GetString("LigaPortugal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.transfermarkt.pl/ligue-1/startseite/wettbewerb/FR1.
        /// </summary>
        internal static string Ligue1 {
            get {
                return ResourceManager.GetString("Ligue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.transfermarkt.com/premier-league/startseite/wettbewerb/GB1.
        /// </summary>
        internal static string PremierLeague {
            get {
                return ResourceManager.GetString("PremierLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.transfermarkt.pl/serie-a/startseite/wettbewerb/IT1.
        /// </summary>
        internal static string SerieA {
            get {
                return ResourceManager.GetString("SerieA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.transfermarkt.pl/super-league-1/startseite/wettbewerb/GR1.
        /// </summary>
        internal static string SuperLeague1 {
            get {
                return ResourceManager.GetString("SuperLeague1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.transfermarkt.pl/super-lig/startseite/wettbewerb/TR1.
        /// </summary>
        internal static string SuperLig {
            get {
                return ResourceManager.GetString("SuperLig", resourceCulture);
            }
        }
    }
}
