<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SoccerInfo.Application.Abstractions\SoccerInfo.Application.Abstractions.csproj" />
    <ProjectReference Include="..\SoccerInfo.Domain\SoccerInfo.Domain.csproj" />
    <ProjectReference Include="..\SoccerInfo.Shared\SoccerInfo.Shared.csproj" />
  </ItemGroup>

</Project>
