// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoccerInfo.Persistence.Data;

#nullable disable

namespace SoccerInfo.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250708182101_Clubs_Overviews_TrasnfermarktUrl_nullable")]
    partial class Clubs_Overviews_TrasnfermarktUrl_nullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NationalityPlayer", b =>
                {
                    b.Property<int>("NationalityId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("NationalityId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("NationalityPlayer");
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.CountryFlag_Lookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageSvgBase64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwoLetterISOCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CountryFlags_Lookup");
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.Extraction.LeagueLinkLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeagueLinksLookup", "extraction");
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.GeneralPosition.GeneralPosition_Lookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GeneralPositions_Lookup");
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryFlagBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeagueImageBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.MarketValueChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<float?>("MarketValue")
                        .HasColumnType("real");

                    b.Property<float?>("MarketValueNormalized")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("real")
                        .HasComputedColumnSql("\r\n                CASE \r\n                    WHEN MarketValueUnit IS NULL OR MarketValue IS NULL THEN NULL\r\n                    WHEN MarketValueUnit = 'm' THEN MarketValue * 1000000\r\n                    WHEN MarketValueUnit = 'k' THEN MarketValue * 1000\r\n                    ELSE NULL\r\n                END", true);

                    b.Property<string>("MarketValueUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerTransferMarktId")
                        .HasColumnType("int");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("MarketValueChanges");
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.Nationality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountryFlagId")
                        .HasColumnType("int");

                    b.Property<string>("Country_Lookup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryFlagId");

                    b.ToTable("Nationalities");
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FaceImageBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GeneralPositionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<float?>("MarketValue")
                        .HasColumnType("real");

                    b.Property<float?>("MarketValueNormalized")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("real")
                        .HasComputedColumnSql("\r\n                CASE \r\n                    WHEN MarketValueUnit IS NULL OR MarketValue IS NULL THEN NULL\r\n                    WHEN MarketValueUnit = 'm' THEN MarketValue * 1000000\r\n                    WHEN MarketValueUnit = 'k' THEN MarketValue * 1000\r\n                    ELSE NULL\r\n                END", true);

                    b.Property<string>("MarketValueUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("TransfermarktId")
                        .HasColumnType("int");

                    b.Property<string>("TransfermarktURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GeneralPositionId");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.PlayerCharacteristicsAggregate.GoalKeeperStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CleanSheets")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GoalsConceded")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<int?>("MatchesPlayed")
                        .HasColumnType("int");

                    b.Property<int?>("MinutesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("PlayerCharacteristicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("PlayerCharacteristicId");

                    b.ToTable("GoalKeeperStats");
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.PlayerCharacteristicsAggregate.OutfieldPlayerStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Assists")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Goals")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<int?>("MatchesPlayed")
                        .HasColumnType("int");

                    b.Property<int?>("MinutesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("PlayerCharacteristicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("PlayerCharacteristicId");

                    b.ToTable("OutfieldPlayerStats");
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.PlayerCharacteristicsAggregate.PlayerCharacteristic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClubJoinDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ContractExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<float?>("Height")
                        .HasColumnType("real");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeadingFoot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("PlayerCharacteristics", (string)null);
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.PlayerCharacteristicsAggregate.SocialMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerCharacteristicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCharacteristicId");

                    b.ToTable("Socials", (string)null);
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.PlayerCharacteristicsAggregate.StatsLeague", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Base64Image")
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("_HashCode")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("_HashCode")
                        .HasComputedColumnSql("CONVERT(varchar(64), HASHBYTES('SHA2_256', CONCAT(Name, Base64Image)), 1)");

                    b.HasKey("Id");

                    b.HasIndex("_HashCode")
                        .IsUnique();

                    b.ToTable("StatsLeagues", (string)null);
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.Stats.PlayerStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<float?>("Height")
                        .HasColumnType("real");

                    b.Property<float?>("LastMarkeValueProgress")
                        .HasColumnType("real");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<float?>("MarketValue")
                        .HasColumnType("real");

                    b.Property<float?>("MarketValueNormalized")
                        .HasColumnType("real");

                    b.Property<string>("MarketValueUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("TotalAssists")
                        .HasColumnType("int");

                    b.Property<int?>("TotalCleanSheets")
                        .HasColumnType("int");

                    b.Property<int?>("TotalGoals")
                        .HasColumnType("int");

                    b.Property<int?>("TotalGoalsAndAssists")
                        .HasColumnType("int");

                    b.Property<int?>("TotalGoalsConceded")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Height");

                    b.HasIndex("MarketValueNormalized");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.HasIndex("TotalAssists");

                    b.HasIndex("TotalCleanSheets");

                    b.HasIndex("TotalGoals");

                    b.HasIndex("TotalGoalsAndAssists");

                    b.HasIndex("TotalGoalsConceded");

                    b.ToTable("PlayerStatistics");
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamImageBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransfermarktId")
                        .HasColumnType("int");

                    b.Property<string>("TransfermarktURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.Transfers.ClubOverview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClubImageBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryImageBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransfermarktId")
                        .HasColumnType("int");

                    b.Property<string>("TrasnfermarktUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClubsOverviews");
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.Transfers.Transfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FeeNormalized")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MarketValueNormalized")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerTransferMarktId")
                        .HasColumnType("int");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("NationalityPlayer", b =>
                {
                    b.HasOne("SoccerInfo.Domain.Models.Nationality", null)
                        .WithMany()
                        .HasForeignKey("NationalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerInfo.Domain.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.MarketValueChange", b =>
                {
                    b.HasOne("SoccerInfo.Domain.Models.Player", null)
                        .WithMany("MarketValueProgress")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.Nationality", b =>
                {
                    b.HasOne("SoccerInfo.Domain.Models.CountryFlag_Lookup", "CountryFlag")
                        .WithMany()
                        .HasForeignKey("CountryFlagId");

                    b.Navigation("CountryFlag");
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.Player", b =>
                {
                    b.HasOne("SoccerInfo.Domain.Models.GeneralPosition.GeneralPosition_Lookup", "GeneralPosition")
                        .WithMany()
                        .HasForeignKey("GeneralPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerInfo.Domain.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneralPosition");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.PlayerCharacteristicsAggregate.GoalKeeperStats", b =>
                {
                    b.HasOne("SoccerInfo.Domain.Models.PlayerCharacteristicsAggregate.StatsLeague", "League")
                        .WithMany("GoalKeeperStats")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerInfo.Domain.Models.PlayerCharacteristicsAggregate.PlayerCharacteristic", null)
                        .WithMany("GoalKeeperStats")
                        .HasForeignKey("PlayerCharacteristicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.PlayerCharacteristicsAggregate.OutfieldPlayerStats", b =>
                {
                    b.HasOne("SoccerInfo.Domain.Models.PlayerCharacteristicsAggregate.StatsLeague", "League")
                        .WithMany("OutfieldPlayerStats")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerInfo.Domain.Models.PlayerCharacteristicsAggregate.PlayerCharacteristic", null)
                        .WithMany("OutfieldPlayerStats")
                        .HasForeignKey("PlayerCharacteristicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.PlayerCharacteristicsAggregate.PlayerCharacteristic", b =>
                {
                    b.HasOne("SoccerInfo.Domain.Models.Player", null)
                        .WithOne("Characteristics")
                        .HasForeignKey("SoccerInfo.Domain.Models.PlayerCharacteristicsAggregate.PlayerCharacteristic", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SoccerInfo.Domain.Models.PlayerCharacteristicsAggregate.BrithPlace", "BrithPlace", b1 =>
                        {
                            b1.Property<int>("PlayerCharacteristicId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Country")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PlayerCharacteristicId");

                            b1.ToTable("PlayerCharacteristics");

                            b1.WithOwner()
                                .HasForeignKey("PlayerCharacteristicId");
                        });

                    b.OwnsOne("SoccerInfo.Domain.Models.PlayerCharacteristicsAggregate.NationalTeam", "NationalTeam", b1 =>
                        {
                            b1.Property<int>("PlayerCharacteristicId")
                                .HasColumnType("int");

                            b1.Property<int>("Caps")
                                .HasColumnType("int");

                            b1.Property<string>("Country")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Goals")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PlayerCharacteristicId");

                            b1.ToTable("PlayerCharacteristics");

                            b1.WithOwner()
                                .HasForeignKey("PlayerCharacteristicId");
                        });

                    b.Navigation("BrithPlace");

                    b.Navigation("NationalTeam");
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.PlayerCharacteristicsAggregate.SocialMedia", b =>
                {
                    b.HasOne("SoccerInfo.Domain.Models.PlayerCharacteristicsAggregate.PlayerCharacteristic", null)
                        .WithMany("Socials")
                        .HasForeignKey("PlayerCharacteristicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.Stats.PlayerStatistic", b =>
                {
                    b.HasOne("SoccerInfo.Domain.Models.Player", "Player")
                        .WithOne("Stats")
                        .HasForeignKey("SoccerInfo.Domain.Models.Stats.PlayerStatistic", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SoccerInfo.Domain.Models.Stats.DateRange", "Age", b1 =>
                        {
                            b1.Property<int>("PlayerStatisticId")
                                .HasColumnType("int");

                            b1.Property<int>("Days")
                                .HasColumnType("int");

                            b1.Property<int>("Months")
                                .HasColumnType("int");

                            b1.Property<int>("TotalDays")
                                .HasColumnType("int");

                            b1.Property<int>("Years")
                                .HasColumnType("int");

                            b1.HasKey("PlayerStatisticId");

                            b1.HasIndex("TotalDays");

                            b1.ToTable("PlayerStatistics");

                            b1.WithOwner()
                                .HasForeignKey("PlayerStatisticId");
                        });

                    b.OwnsOne("SoccerInfo.Domain.Models.Stats.DateRange", "ContractPeriod", b1 =>
                        {
                            b1.Property<int>("PlayerStatisticId")
                                .HasColumnType("int");

                            b1.Property<int>("Days")
                                .HasColumnType("int");

                            b1.Property<int>("Months")
                                .HasColumnType("int");

                            b1.Property<int>("TotalDays")
                                .HasColumnType("int");

                            b1.Property<int>("Years")
                                .HasColumnType("int");

                            b1.HasKey("PlayerStatisticId");

                            b1.HasIndex("TotalDays");

                            b1.ToTable("PlayerStatistics");

                            b1.WithOwner()
                                .HasForeignKey("PlayerStatisticId");
                        });

                    b.Navigation("Age")
                        .IsRequired();

                    b.Navigation("ContractPeriod");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.Team", b =>
                {
                    b.HasOne("SoccerInfo.Domain.Models.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId");

                    b.Navigation("League");
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.Transfers.Transfer", b =>
                {
                    b.HasOne("SoccerInfo.Domain.Models.Player", null)
                        .WithMany("Transfers")
                        .HasForeignKey("PlayerId");

                    b.OwnsOne("SoccerInfo.Domain.Models.Transfers.Transfer+Money", "Fee", b1 =>
                        {
                            b1.Property<int>("TransferId")
                                .HasColumnType("int");

                            b1.Property<string>("Suffix")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TransferId");

                            b1.ToTable("Transfers");

                            b1.WithOwner()
                                .HasForeignKey("TransferId");
                        });

                    b.OwnsOne("SoccerInfo.Domain.Models.Transfers.Transfer+ClubInfo", "From", b1 =>
                        {
                            b1.Property<int>("TransferId")
                                .HasColumnType("int");

                            b1.Property<int?>("ClubId")
                                .HasColumnType("int");

                            b1.Property<int>("ClubTransfermarktId")
                                .HasColumnType("int");

                            b1.Property<int?>("TeamId")
                                .HasColumnType("int");

                            b1.HasKey("TransferId");

                            b1.HasIndex("ClubId");

                            b1.HasIndex("TeamId");

                            b1.ToTable("Transfers");

                            b1.HasOne("SoccerInfo.Domain.Models.Transfers.ClubOverview", "Club")
                                .WithMany()
                                .HasForeignKey("ClubId");

                            b1.HasOne("SoccerInfo.Domain.Models.Team", "Team")
                                .WithMany()
                                .HasForeignKey("TeamId");

                            b1.WithOwner()
                                .HasForeignKey("TransferId");

                            b1.Navigation("Club");

                            b1.Navigation("Team");
                        });

                    b.OwnsOne("SoccerInfo.Domain.Models.Transfers.Transfer+Money", "MarketValue", b1 =>
                        {
                            b1.Property<int>("TransferId")
                                .HasColumnType("int");

                            b1.Property<string>("Suffix")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TransferId");

                            b1.ToTable("Transfers");

                            b1.WithOwner()
                                .HasForeignKey("TransferId");
                        });

                    b.OwnsOne("SoccerInfo.Domain.Models.Transfers.Transfer+ClubInfo", "To", b1 =>
                        {
                            b1.Property<int>("TransferId")
                                .HasColumnType("int");

                            b1.Property<int?>("ClubId")
                                .HasColumnType("int");

                            b1.Property<int>("ClubTransfermarktId")
                                .HasColumnType("int");

                            b1.Property<int?>("TeamId")
                                .HasColumnType("int");

                            b1.HasKey("TransferId");

                            b1.HasIndex("ClubId");

                            b1.HasIndex("TeamId");

                            b1.ToTable("Transfers");

                            b1.HasOne("SoccerInfo.Domain.Models.Transfers.ClubOverview", "Club")
                                .WithMany()
                                .HasForeignKey("ClubId");

                            b1.HasOne("SoccerInfo.Domain.Models.Team", "Team")
                                .WithMany()
                                .HasForeignKey("TeamId");

                            b1.WithOwner()
                                .HasForeignKey("TransferId");

                            b1.Navigation("Club");

                            b1.Navigation("Team");
                        });

                    b.Navigation("Fee");

                    b.Navigation("From")
                        .IsRequired();

                    b.Navigation("MarketValue");

                    b.Navigation("To")
                        .IsRequired();
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.League", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.Player", b =>
                {
                    b.Navigation("Characteristics");

                    b.Navigation("MarketValueProgress");

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("Transfers");
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.PlayerCharacteristicsAggregate.PlayerCharacteristic", b =>
                {
                    b.Navigation("GoalKeeperStats");

                    b.Navigation("OutfieldPlayerStats");

                    b.Navigation("Socials");
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.PlayerCharacteristicsAggregate.StatsLeague", b =>
                {
                    b.Navigation("GoalKeeperStats");

                    b.Navigation("OutfieldPlayerStats");
                });

            modelBuilder.Entity("SoccerInfo.Domain.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
